# Generated by Django 4.2.14 on 2024-07-14 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Poet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_year', models.CharField(max_length=100)),
                ('death_year', models.CharField(default='Alive', max_length=100)),
                ('birth_place', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='poet_pics/')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='poet.category')),
                ('poet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='poet.poet')),
            ],
        ),
        migrations.CreateModel(
            name='FamousBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publication_year', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='famous_books', to='poet.category')),
                ('poet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='famous_books', to='poet.poet')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='poet.category')),
                ('poet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='poet.poet')),
            ],
        ),
    ]
